const types = {
    FETCHING_START: 'FETCHING_START_3',
    FETCH_SUCCESS: 'FETCH_SUCCESS_3',
    FETCH_FAIL: 'FETCH_FAIL_3',
    TOGGLE_SOLVED: 'TOGGLE_SOLVED',
    UPDATE_PHOTO: 'UPDATE_PHOTO',
    ADD_PROBLEM: 'ADD_PROBLEM',
    ADD_A_LIST: 'ADD_A_LIST',
};

export default types;